---
volumes:
  config: {}
  log: {}
  run: {}

networks:
  caddy:
    external: true

services:
  unifi:
    image: ryansch/unifi-rpi:${UNIFI_VERSION}
    restart: unless-stopped
    environment:
      JAVA_OPTS: -Xmx1024M
    ports:
      - 8080:8080      # Device -> controller
      - 3478:3478/udp  # STUN
    networks:
      - default
      - caddy
    volumes:
      - config:/var/lib/unifi
      - log:/usr/lib/unifi/logs
      - run:/usr/lib/unifi/run
    labels:
      caddy: unifi.mafro.net
      caddy.tls.ca: https://ca.mafro.net:4433/acme/acme/directory
      caddy.tls.ca_root: /root/step_ca.crt
      caddy.reverse_proxy: "{{upstreams https 8443}}"
      caddy.reverse_proxy.transport: http
      caddy.reverse_proxy.transport.tls_insecure_skip_verify:
