---
volumes:
  config: {}
  log: {}
  run: {}

services:
  unifi:
    image: ryansch/unifi-rpi:${UNIFI_VERSION}
    restart: unless-stopped
    environment:
      JAVA_OPTS: -Xmx512M
    ports:
      - 8080:8080      # Device -> controller
      - 8888:8443      # Web UI
      - 3478:3478/udp  # STUN
    volumes:
      - config:/var/lib/unifi
      - log:/usr/lib/unifi/logs
      - run:/usr/lib/unifi/run
